//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estimates()
        {
            this.Project_archive = new HashSet<Project_archive>();
            this.Tax_report = new HashSet<Tax_report>();
        }
    
        public int Estimates_code { get; set; }
        public Nullable<int> Contract_code { get; set; }
        public Nullable<int> Tech_spec_code { get; set; }
        public string Estimates_link { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Tech_spec Tech_spec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_archive> Project_archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_report> Tax_report { get; set; }
    }
}
