//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work_team()
        {
            this.Work_team_employee = new HashSet<Work_team_employee>();
        }
    
        public int Work_team_code { get; set; }
        public Nullable<int> Work_plan_code { get; set; }
        public string Work_team_name { get; set; }
        public Nullable<int> Work_team_supervisor { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Work_plan Work_plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_team_employee> Work_team_employee { get; set; }
    }
}
