//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_team_employee
    {
        public int Work_team_employee_code { get; set; }
        public Nullable<int> Work_team_code { get; set; }
        public Nullable<int> Employee_code { get; set; }
        public Nullable<int> Number_in_work_team { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Work_team Work_team { get; set; }
    }
}
